= Building PropellerIDE

PropellerIDE has been built on these platforms:

- Windows (Vista, 7, 8, 10)
- Mac OS X (>= 10.6)
- Ubuntu (>= 14.04, 12.04 with backports)
- Raspbian OS, pcDuino

PropellerIDE has been built using these compilers:

- GCC
- Clang
- MinGW-x64
- MSVC

== General Requirements

The following table lists the requirements to build PropellerIDE components:

[options="header"]
|===
| Component         | Dependencies
| PropellerIDE      | G++, Make Qt (>= 5.3), QSerialPort
| OpenSpin          | G++, Make
| PropBASIC         | Free Pascal Compiler (FPC)
| Debian package    | debhelper, help2man, libftdi1, libudev-dev
| Windows installer | InnoSetup 5
| Apple Disk Image  | _None_
|===

== Installing Packthing

If you intend to create binary releases, you must install link:https://github.com/lamestation/packthing[Packthing], which requires Python 2.7 to be installed. You can install Packthing like so:

    $ git clone https://github.com/lamestation/packthing
    $ cd packthing
    $ sudo pip install -r requirements.txt
    $ sudo python setup.py install

== Getting the Source

Check out the project, using the `--recursive` flag to pull in submodules, and then `cd` into the project directory. *Do not use the source tarballs generated by GitHub as they do not include submodules*.

    $ git clone --recursive https://github.com/parallaxinc/PropellerIDE
    $ cd PropellerIDE

== Building

=== Linux

==== Debian-based distros

To build only the `propelleride` executable:

    $ sudo apt-get install g++ make qt5-default libqt5serialport5-dev

You can build the executable as follows:
    
    $ qmake -r
    $ make -j8

`propelleride` will be built at `./src/propelleride/propelleride`.

To build the complete Debian package, which includes OpenSpin and PropBASIC, install these additional dependencies:

    $ sudo apt-get install help2man debhelper imagemagick libftdi1 \
            libudev-dev fpc                        
    $ fakeroot packthing -r deb -j8
    
The `.deb` package will be built at `./build/staging/propelleride-X.Y.Z-ARCH.deb`.

==== RHEL-ish distros

To build the `propelleride` executable:

    $ sudo dnf install gcc-g++ make qt5 qt5-devel

In older YUM repositories, there were no top-level `qt5` or `qt5-devel` packages. If the above command fails for you, install the prerequisites directly.

    $ sudo dnf install qt5-qtbase qt5-qttools qt5-qtbase-gui \
            qt5-qtserialport qtchooser qt5-qtbase-devel

You can build the executable as follows:
    
    $ qmake-qt5 -r
    $ make -j8

RPM packaging is not yet available.

=== Building on Mac

Building on Mac is generally similar to Linux.

_Instructions are not yet available._

=== Building on Windows

You will need to download Qt5 from the Qt website. You will also need Inno 
Setup to build the Windows installer.

-   https://www.qt.io/download/
-   http://www.jrsoftware.org/isinfo.php

Qt is distributed with either a MinGW or MSVC toolchain on Windows. Be sure to 
add the paths to the toolchain and Inno Setup to the system environment.

    C:\Qt\Tools\mingw482_32\bin;C:\Qt\5.3\mingw482_32\bin;C:\Program Files (x86)\Inno Setup 5

The MinGW toolchain is painfully slow, but you can build with `mingw32-make`, 
which supposedly supports parallel builds but is slow as a dog anyway so it 
makes little difference.

    > mingw32-make

If you've decided to install Visual Studio, you'll have an instance 
of `nmake`. You can enable parallel builds by setting the CL environment 
variable, which will speed things up considerably. 

    > set CL=/MP

Then start the build.

    > nmake

=== Using QtCreator

PropellerIDE may also be built with QtCreator, but it should be noted that 
QtCreator and `qmake` builds seem to be incompatible with each other, 
so `make distclean` should be called before switching between them.

=== Using CMake

_Instructions on CMake builds are not yet available._
